### ISSUE TITLE
proposals

### ISSUE THREAD

**Issue by gitut2007** [ddawson/Link-Tools#1]
Hi.
As per "don't hesitate to submit examples":
-copy embedded in pages Youtube links into normal/short version YT links.
-copy webarchive links into original page links.
-copy/bookmark webarchive.org links into same but with date/hour taken out, so  one can visit the bookmark later at a more recent date.
-like Google but for others eg Startpage.
Thanks.

**Comment by ddawson** [comment]
Thanks for the submissions.

> -copy embedded in pages Youtube links into normal/short version YT links.
>
I might need an elaboration on that. Do you mean embedded videos? URLs
that are not actual links (i.e. in plain text)? Or what? And if
something other than embedded videos, can you provide any examples of
actual pages that have these?

> -copy webarchive links into original page links.
>
Okay. Seems straightforward enough. I'll see if I can add that.

> -copy/bookmark webarchive.org links into same but with date/hour taken
> out, so one can visit the bookmark later at a more recent date.
>
So, to the date selection pages, right?

> -like Google but for others eg Startpage.
>
Hmm. Just at a glance, it looks like Startpage doesn't put its queries
in the URL the way some other search engines do. So Link Tools wouldn't
be able to do anything with its search results pages, since it /only/
looks at the URL itself. If you happen to know of any part of the site
that /does/ have something usable, let me know. But I think the whole
site might be that way deliberately.

I think I can probably add some others like e.g. Bing and DuckDuckGo
while I'm at this, though. Any others you'd like to see?

**Comment by ddawson** [comment]
If you're asking about embedded YouTube videos, note that you can usually use the linked title that appears at the top when you mouse over it. Link Tools is able to work with that.

**Comment by ddawson** [comment]
Just looked at Startpage a little more. It does accept search links of a similar form as Google. If you find Startpage search links, Link Tools can work with those links. However, the default behavior of its search forms is to use HTTP POST instead of the usual GET, resulting in the page address not containing any information about the search; this is meant to hide queries from logs of other web sites, which could otherwise get it through the "Referer:" header. You have to go to the settings, find the switch "Use POST vs GET", and change it to off, in order to be able to get search links from the site.

This does remove that privacy protection, but I believe it's possible to get it from Firefox, assuming you don't want to be changing that setting all the time. Try searching Mozilla Add-ons for "referer" (yes, spelled like that).

**Comment by ddawson** [comment]
Well, I was hoping for a followup, @gitut2007 , but it's not looking like one is forthcoming. I'll probably make it a version with the changes I have now, then.
